### ISSUE TITLE
Additional Values for Alarm Status

### ISSUE THREAD

**Issue by brucejackson** [Tertiush/ParadoxIP150#2]
First, Thank you for your time & effort on this project.  Finding this project finally convinced me to buy and IP150 for my alarm.

Two additional values for the Alarm state for lines 456 through 468 are:
6 - Entry Delay
7 - Exit Delay

I got this by changing line 468 to include the Alarm Status value:
`newstate = "Unsure: " + val`

Then I armed/disarmed my alarm comparing the value this script reports versus the IP150 web interface.

**Comment by Tertiush** [comment]
PR has been merged. thanks for helping
