### ISSUE TITLE
Home Asistant topic states help Please 

### ISSUE THREAD

**Issue by FigJam23** [Tertiush/ParadoxIP150#6]

**Comment by mydakota** [comment]
I've tried editing the Auth=None and adding in the user and password field as stated in doc but does not work for now I've disabled my Mqtt user and passwords and is working but I think it would be good to have option of username and password for MQTT.

**Comment by mydakota** [comment]
Also at start up it grabs all zone labels and partition label good and Arm Disarm work perfectly although I haven't got armed status to work as yet . Now I'm not getting any zone opens or closes from zones in the Arm or disarm state I'm assuming it should work in both conditions. I am not getting any changes come up in the terminal except for when I hit my arm / disarm buttons in Home Assistant the the commands show up but no response when armed. Would you have any ideas what I can look at to get stats working . I'm using the evo48 and I realise it's not supported but version one is working fine for me with the exceptions of stats and zone opens and closes . Im sure it's something simple as it gets zone labels and state 1 on first start

**Comment by mydakota** [comment]
OK so with my evo48 I am able to arm disarm my system via home assistant and MQTT
I have now managed to get zone reporting working well sending messages from ip150 to MQTT like this below.
`Client mosqsub/30466-raspberry received PUBLISH (d0, q0, r1, m0, 'cmnd/sonoff/power', ... (3 bytes))
OFF
Client mosqsub/30466-raspberry received PUBLISH (d0, q0, r1, m0, 'Paradox/C/P1/Arm', ... (2 bytes))
ON
Client mosqsub/30466-raspberry received PUBLISH (d0, q0, r1, m0, 'Paradox/C/P1/Disarm', ... (2 bytes))
ON
Client mosqsub/30466-raspberry received PUBLISH (d0, q0, r1, m0, 'Paradox/State', ... (40 bytes))
Alarm: Control partition 1 to state: Arm
Client mosqsub/30466-raspberry received PUBLISH (d0, q0, r0, m0, 'Paradox/ZS/Z3', ... (26 bytes))
S:OPEN,P:1,N:"Theater PIR"
Client mosqsub/30466-raspberry received PUBLISH (d0, q0, r0, m0, 'Paradox/AS/P1', ... (11 bytes))
Unsure: (9)
Client mosqsub/30466-raspberry received PUBLISH (d0, q0, r0, m0, 'Paradox/ZS/Z3', ... (28 bytes))
S:CLOSED,P:1,N:"Theater PIR"
Client mosqsub/30466-raspberry received PUBLISH (d0, q0, r0, m0, 'Paradox/AS/P1', ... (11 bytes))
Unsure: (8)
Client mosqsub/30466-raspberry received PUBLISH (d0, q0, r0, m0, 'Paradox/ZS/Z1', ... (30 bytes))
S:OPEN,P:1,N:"Living Room PIR"
Client mosqsub/30466-raspberry received PUBLISH (d0, q0, r0, m0, 'Paradox/AS/P1', ... (11 bytes))
`

- platform: mqtt
  name: Theater PIR
  icon: mid:home
  state_topic: "Paradox/ZS/Z3"
  payload_on: "open"
  payload_off: "closed"
  qos: 0
  retain: true

but does not work could someone help me with state topic and command_topic if required

so close to haveing My EVO working perfectly

**Comment by mydakota** [comment]
**HELP ME PLEASE NOTHING WILL SHOW STATES**

- platform: mqtt
  name: Garage Door
  state_topic: "Paradox/ZS/Theater_PIR"
  payload_on: "open"
  payload_off: "closed"
  qos: 0
  retain: true

- platform: mqtt
  name: Living Room PIR
  icon: mid:home
  state_topic: "Paradox/ZS/Theater PIR"
  payload_on: "0"
  payload_off: "1"
  qos: 0
  retain: true

- platform: mqtt
  name: Hallway PIR
  state_topic: "Events/Paradox/ZS/Z2"
  payload_on: "1"
  payload_off: "0"
  qos: 0
  retain: true

- platform: mqtt
  name: Theater PIR
  state_topic: "Paradox/ZS/Theater/PIR"
  payload_on: "OPEN"
  payload_off: "CLOSED"
  qos: 0
  retain: true

**Comment by mydakota** [comment]
Has this project been dumped or given up on 
Or know one knows how to use it . A bit of a shame as it has some good potential and I've read many was wanting a working EVO version and here it is just know one with the knowledge on how to use these dam state messages into Home Assistant . Some stuff on the diying OpenHab but who really is still using it and who wants to learn JavaScript when HOME ASSISTANT works better more reliable and simpler. Come on guys I want to upload a full working EVO version and tutorial videos for others
